package dev.builderai.claudebridge.litematic;

import net.minecraft.SharedConstants;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtIo;
import net.minecraft.nbt.Tag;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Writes a .litematic file (Litematica schematic, format Version 6) from a sparse
 * set of blocks. Coordinates are relative to the schematic origin (min corner).
 * Format reference: https://litemapy.readthedocs.io/en/latest/litematics.html
 */
public final class LitematicWriter {

    /** One block entry: relative position + block state string like "minecraft:oak_stairs[facing=north]". */
    public record Entry(int x, int y, int z, String blockId, Map<String, String> properties) {}

    private LitematicWriter() {}

    public static void write(Path file, String name, String author, List<Entry> entries,
                             int sizeX, int sizeY, int sizeZ) throws IOException {
        if (entries.isEmpty()) throw new IllegalArgumentException("No blocks given");

        // Palette: index 0 is always air (unset positions).
        Map<String, Integer> paletteIndex = new LinkedHashMap<>();
        List<CompoundTag> palette = new ArrayList<>();
        CompoundTag air = new CompoundTag();
        air.putString("Name", "minecraft:air");
        palette.add(air);
        paletteIndex.put("minecraft:air", 0);

        long volume = (long) sizeX * sizeY * sizeZ;
        int[] indices = new int[(int) volume];
        long totalBlocks = 0;

        for (Entry e : entries) {
            if (e.x() < 0 || e.y() < 0 || e.z() < 0 || e.x() >= sizeX || e.y() >= sizeY || e.z() >= sizeZ) {
                throw new IllegalArgumentException("Block out of bounds: " + e.x() + "," + e.y() + "," + e.z()
                        + " (size " + sizeX + "x" + sizeY + "x" + sizeZ + ")");
            }
            String key = paletteKey(e);
            Integer idx = paletteIndex.get(key);
            if (idx == null) {
                CompoundTag state = new CompoundTag();
                state.putString("Name", e.blockId());
                if (e.properties() != null && !e.properties().isEmpty()) {
                    CompoundTag props = new CompoundTag();
                    for (Map.Entry<String, String> p : e.properties().entrySet()) {
                        props.putString(p.getKey(), p.getValue());
                    }
                    state.put("Properties", props);
                }
                palette.add(state);
                idx = palette.size() - 1;
                paletteIndex.put(key, idx);
            }
            // Litematica index order: (y * sizeZ + z) * sizeX + x
            int pos = (e.y() * sizeZ + e.z()) * sizeX + e.x();
            if (indices[pos] == 0 && idx != 0) totalBlocks++;
            indices[pos] = idx;
        }

        int bits = Math.max(2, 32 - Integer.numberOfLeadingZeros(palette.size() - 1));
        long[] packed = pack(indices, bits);

        CompoundTag region = new CompoundTag();
        region.put("Position", vec(0, 0, 0));
        region.put("Size", vec(sizeX, sizeY, sizeZ));
        ListTag paletteTag = new ListTag();
        for (CompoundTag state : palette) paletteTag.add(state);
        region.put("BlockStatePalette", paletteTag);
        region.put("BlockStates", new net.minecraft.nbt.LongArrayTag(packed));
        region.put("TileEntities", new ListTag());
        region.put("Entities", new ListTag());
        region.put("PendingBlockTicks", new ListTag());
        region.put("PendingFluidTicks", new ListTag());

        CompoundTag metadata = new CompoundTag();
        metadata.putString("Name", name);
        metadata.putString("Author", author);
        metadata.putString("Description", "Generated by Claude Bridge");
        long now = System.currentTimeMillis();
        metadata.putLong("TimeCreated", now);
        metadata.putLong("TimeModified", now);
        metadata.put("EnclosingSize", vec(sizeX, sizeY, sizeZ));
        metadata.putInt("RegionCount", 1);
        metadata.putLong("TotalBlocks", totalBlocks);
        metadata.putLong("TotalVolume", volume);
        metadata.putString("Software", "claude-bridge");

        CompoundTag root = new CompoundTag();
        root.putInt("Version", 6);
        root.putInt("MinecraftDataVersion", SharedConstants.getCurrentVersion().dataVersion().version());
        root.put("Metadata", metadata);
        CompoundTag regions = new CompoundTag();
        regions.put(name, region);
        root.put("Regions", regions);

        Files.createDirectories(file.getParent());
        NbtIo.writeCompressed(root, file);
    }

    private static CompoundTag vec(int x, int y, int z) {
        CompoundTag tag = new CompoundTag();
        tag.putInt("x", x);
        tag.putInt("y", y);
        tag.putInt("z", z);
        return tag;
    }

    private static String paletteKey(Entry e) {
        return e.properties() == null || e.properties().isEmpty()
                ? e.blockId() : e.blockId() + e.properties().toString();
    }

    /** Tightly bit-packs indices; entries span long boundaries (litematic format, unlike vanilla chunks). */
    private static long[] pack(int[] indices, int bits) {
        long[] out = new long[(int) Math.ceil((double) indices.length * bits / 64.0)];
        for (int i = 0; i < indices.length; i++) {
            long value = indices[i] & ((1L << bits) - 1);
            long bitIndex = (long) i * bits;
            int longIndex = (int) (bitIndex >> 6);
            int offset = (int) (bitIndex & 63);
            out[longIndex] |= value << offset;
            if (offset + bits > 64) {
                out[longIndex + 1] |= value >>> (64 - offset);
            }
        }
        return out;
    }
}
